-libraryjars m:\WTK20\lib\mmapi.zip;m:\WTK20\lib\wma.zip;m:\WTK20\lib\midpapi.zip
-injars m:\WTK20\apps\SimpleScrollingLayerManger\bin\SimpleScrollingLayerManger.jar
-outjar M:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\SimpleScrollingLayerManger.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
